/** English catalog labels → Hindi display names used by the sheet import. */

export const CATEGORY_HI: Record<string, string> = {
  Grocery: 'किराना',
  Cosmetics: 'कॉस्मेटिक्स',
  'Atta, Flours & Sooji': 'आटा, मैदा और सूजी',
  'Baby Care': 'बेबी केयर',
  'Bath & Body': 'स्नान और बॉडी',
  'Beverages & Tea/Coffee': 'पेय और चाय/कॉफी',
  'Biscuits & Bakery': 'बिस्कुट और बेकरी',
  'Chocolates & Confectionery': 'चॉकलेट और मिठाई',
  'Cosmetics & Makeup': 'कॉस्मेटिक्स और मेकअप',
  'Dairy & Eggs': 'डेयरी और अंडे',
  'Dals & Pulses': 'दाल और दलहन',
  'Deodorants & Fragrances': 'डिओडोरेंट और खुशबू',
  'Edible Oils & Ghee': 'खाने का तेल और घी',
  'Feminine Hygiene': 'महिला स्वच्छता',
  'Hair Care': 'हेयर केयर',
  'Household & Cleaning': 'घर की सफाई',
  "Men's Grooming": 'पुरुषों की ग्रूमिंग',
  'Noodles, Pasta & Instant Food': 'नूडल्स, पास्ता और इंस्टेंट फूड',
  'Oral Care': 'ओरल केयर',
  'Personal Care': 'पर्सनल केयर',
  'Rice & Rice Products': 'चावल और चावल उत्पाद',
  'Salt, Sugar & Jaggery': 'नमक, चीनी और गुड़',
  'Skin Care & Face Care': 'स्किन केयर और फेस केयर',
  'Snacks & Namkeen': 'स्नैक्स और नमकीन',
  'Spices & Masalas': 'मसाले',
  'Sunscreen & Sun Care': 'सनस्क्रीन और सन केयर',
};

export const SUB_CATEGORY_HI: Record<string, string> = {
  'Baby Bath & Skincare': 'बेबी बाथ और स्किनकेयर',
  'Baby Diapers & Wipes': 'बेबी डायपर और वाइप्स',
  'Basmati Rice': 'बासमती चावल',
  'Bathing Soaps': 'नहाने के साबुन',
  'Besan & Gram Flour': 'बेसन और चना आटा',
  'Blended Cooking Masalas': 'मिक्स मसाले',
  'Body Wash & Shower Gels': 'बॉडी वॉश और शावर जेल',
  'Butter & Cheese': 'मक्खन और चीज़',
  'Chana Dal & Kala Chana': 'चना दाल और काला चना',
  Coffee: 'कॉफी',
  'Conditioners & Hair Masks': 'कंडीशनर और हेयर मास्क',
  'Cream & Chocolate Biscuits': 'क्रीम और चॉकलेट बिस्कुट',
  'Curd & Yogurt': 'दही और योगर्ट',
  'Dairy & Dark Chocolates': 'डेयरी और डार्क चॉकलेट',
  'Dal & Pulse Snacks': 'दाल और दलहन स्नैक्स',
  'Deodorants & Body Sprays': 'डिओडोरेंट और बॉडी स्प्रे',
  'Desi Cow Ghee': 'देसी गाय का घी',
  'Detergent Powder & Liquids': 'डिटर्जेंट पाउडर और लिक्विड',
  'Dishwash Bars & Liquids': 'बर्तन धोने की बार और लिक्विड',
  'Extruded & Corn Snacks': 'कॉर्न स्नैक्स',
  'Eye Makeup': 'आंखों का मेकअप',
  'Face Makeup': 'चेहरे का मेकअप',
  'Face Moisturizers & Creams': 'फेस मॉइस्चराइज़र और क्रीम',
  'Face Serums & Treatments': 'फेस सीरम और ट्रीटमेंट',
  'Face Wash & Cleansers': 'फेस वॉश और क्लींज़र',
  'Floor & Toilet Cleaners': 'फर्श और टॉयलेट क्लीनर',
  'Glucose & Marie Biscuits': 'ग्लूकोज और मैरी बिस्कुट',
  'Gur & Jaggery': 'गुड़',
  'Hair Oils & Serums': 'हेयर ऑयल और सीरम',
  'Hand Wash & Sanitizers': 'हैंड वॉश और सैनिटाइज़र',
  'Health Drink Powders': 'हेल्थ ड्रिंक पाउडर',
  'Instant Noodles': 'इंस्टेंट नूडल्स',
  'Instant Soups & Mixes': 'इंस्टेंट सूप और मिक्स',
  'Kolam & Daily Rice': 'कोलम और रोज़ का चावल',
  'Lip Makeup': 'होंठों का मेकअप',
  "Men's Face Wash & Skincare": 'पुरुषों का फेस वॉश और स्किनकेयर',
  'Milk & Buttermilk': 'दूध और छाछ',
  'Moong Dal': 'मूंग दाल',
  'Mustard Oil (Sarson)': 'सरसों का तेल',
  'Oral Care': 'ओरल केयर',
  'Packaged Juices & Syrups': 'पैक्ड जूस और सिरप',
  'Paneer & Tofu': 'पनीर और टोफू',
  'Pasta & Macaroni': 'पास्ता और मैकरोनी',
  'Poha & Flattened Rice': 'पोहा और चिवड़ा',
  'Potato Chips & Crisps': 'आलू चिप्स',
  'Powdered Spices': 'पिसे मसाले',
  'Rajma & Chole': 'राजमा और छोले',
  'Rusks, Khari & Bread': 'रस्क, खारी और ब्रेड',
  'Sanitary Pads & Liners': 'सैनिटरी पैड और लाइनर',
  Shampoos: 'शैंपू',
  'Shaving & Beard Care': 'शेविंग और दाढ़ी की देखभाल',
  'Sooji, Rava & Semolina': 'सूजी, रवा और सेमोलिना',
  'Sugar & Natural Sweeteners': 'चीनी और प्राकृतिक मिठास',
  'Sunflower & Soya Oil': 'सूरजमुखी और सोया तेल',
  'Sunscreen Creams & Gels': 'सनस्क्रीन क्रीम और जेल',
  'Table & Rock Salt': 'नमक और सेंधा नमक',
  'Tea & Chai Patti': 'चाय पत्ती',
  'Toor & Arhar Dal': 'तूर और अरहर दाल',
  'Toothbrushes & Mouthwash': 'टूथब्रश और माउथवॉश',
  Toothpaste: 'टूथपेस्ट',
  'Traditional Namkeen & Bhujia': 'नमकीन और भुजिया',
  'Whole Spices (Khada Masala)': 'साबुत मसाले (खड़ा मसाला)',
  'Whole Wheat Atta': 'गेहूं का आटा',
};

/** Longest English phrases first so shorter words do not eat them. */
const NAME_PHRASES: Array<[string, string]> = [
  ['Vacuum Evaporated Iodized Salt', 'वैक्यूम इवैपोरेटेड आयोडीन युक्त नमक'],
  ['Himalayan Pink Rock Salt', 'हिमालयी पिंक रॉक सॉल्ट'],
  ['100% Sharbati Whole Wheat Atta', '100% शरबती गेहूं का आटा'],
  ['Chakki Fresh Whole Wheat Atta', 'चक्की फ्रेश गेहूं का आटा'],
  ['Superior MP Sharbati Atta', 'सुपीरियर एमपी शरबती आटा'],
  ['Full Grain Kolam Rice', 'फुल ग्रेन कोलम चावल'],
  ['Basmati Rice Classic', 'बासमती चावल क्लासिक'],
  ['Basmati Rice', 'बासमती चावल'],
  ['Kachi Ghani Pure Mustard Oil', 'कच्ची घानी शुद्ध सरसों का तेल'],
  ['Refined Sunflower Oil', 'रिफाइंड सूरजमुखी तेल'],
  ['Blended Oil', 'ब्लेंडेड तेल'],
  ['Pure Desi Ghee', 'शुद्ध देसी घी'],
  ['Pure Cow Ghee', 'शुद्ध गाय का घी'],
  ['Sulfur Free Sugar', 'सल्फर-फ्री चीनी'],
  ['Organic Jaggery Powder', 'ऑर्गेनिक गुड़ पाउडर'],
  ['Turmeric / Haldi Powder', 'हल्दी पाउडर'],
  ['Lal Mirch / Red Chilli Powder', 'लाल मिर्च पाउडर'],
  ['Coriander / Dhaniya Powder', 'धनिया पाउडर'],
  ['Red Chilli Powder', 'लाल मिर्च पाउडर'],
  ['Deggi Mirch', 'देगी मिर्च'],
  ['Garam Masala', 'गरम मसाला'],
  ['Chana Masala', 'चना मसाला'],
  ['Pav Bhaji Masala', 'पाव भाजी मसाला'],
  ['Sambhar Masala', 'सांभर मसाला'],
  ['Chunky Chat Masala', 'चंकी चाट मसाला'],
  ['Kitchen King Masala', 'किचन किंग मसाला'],
  ['Shahi Paneer Masala', 'शाही पनीर मसाला'],
  ['Dal Makhani Masala', 'दाल मखनी मसाला'],
  ['Rajmah Masala', 'राजमा मसाला'],
  ['Jaljeera Masala', 'जलजीरा मसाला'],
  ['Shahi Garam Masala', 'शाही गरम मसाला'],
  ['Kasoori Methi', 'कसूरी मेथी'],
  ['Kastoori Methi', 'कस्तूरी मेथी'],
  ['Whole Cumin Seeds (Jeera)', 'साबुत जीरा'],
  ['Green Cardamom (Chhoti Elaichi)', 'हरी इलायची'],
  ['Whole Black Pepper (Kali Mirch)', 'साबुत काली मिर्च'],
  ['Hing / Asafoetida Powder', 'हींग पाउडर'],
  ['Whole Cloves (Laung)', 'साबुत लौंग'],
  ['Cinnamon Sticks (Dalchini)', 'दालचीनी'],
  ['Chana Dal', 'चना दाल'],
  ['Toor Dal', 'तूर दाल'],
  ['Moong Dal Dhuli', 'मूंग दाल धुली'],
  ['Chana Whole (Kala Chana)', 'साबुत काला चना'],
  ['Kabuli Chana (Chole)', 'काबुली चना (छोले)'],
  ['Rajma Kashmiri Red', 'कश्मीरी लाल राजमा'],
  ['Thick Poha', 'मोटा पोहा'],
  ['Fine Sooji / Rawa', 'बारीक सूजी / रवा'],
  ['100% Chana Dal', '100% चना दाल'],
  ['Homogenised Toned Milk', 'होमोजनाइज्ड टोंड मिल्क'],
  ['Full Cream Milk', 'फुल क्रीम मिल्क'],
  ['Malai Paneer', 'मलाई पनीर'],
  ['Classic Curd / Dahi', 'क्लासिक दही'],
  ['Pasteurised Salted', 'पाश्चराइज़्ड नमकीन'],
  ['Processed Cheese Slices', 'प्रोसेस्ड चीज़ स्लाइस'],
  ['Spiced Buttermilk / Chaas', 'मसालेदार छाछ'],
  ['Aloo Bhujia', 'आलू भुजिया'],
  ['Bikaneri Bhujia', 'बिकानेरी भुजिया'],
  ['Khatta Meetha Mixture', 'खट्टा मीठा मिक्स्चर'],
  ['Potato Chips', 'आलू चिप्स'],
  ['Crispy Puffs', 'क्रिस्पी पफ्स'],
  ['Glucose Biscuits', 'ग्लूकोज बिस्कुट'],
  ['Marie Gold Biscuits', 'मैरी गोल्ड बिस्कुट'],
  ['Butter Cookies', 'बटर कुकीज़'],
  ['Vanilla Creme Biscuits', 'वेनिला क्रीम बिस्कुट'],
  ['Premium Bake Rusk', 'प्रीमियम बेक रस्क'],
  ['Instant Noodles', 'इंस्टेंट नूडल्स'],
  ['Masala Penne', 'मसाला पेने'],
  ['Instant Soup', 'इंस्टेंट सूप'],
  ['Breakfast Mix', 'ब्रेकफास्ट मिक्स'],
  ['Gulab Jamun Mix', 'गुलाब जामुन मिक्स'],
  ['Chocolate Bar', 'चॉकलेट बार'],
  ['Dark Chocolate', 'डार्क चॉकलेट'],
  ['Crispy Wafer Bar', 'क्रिस्पी वेफर बार'],
  ['Black Tea', 'काली चाय'],
  ['Instant Coffee', 'इंस्टेंट कॉफी'],
  ['Mixed Fruit Juice', 'मिक्स फ्रूट जूस'],
  ['Orange Juice', 'ऑरेंज जूस'],
  ['Health Drink Powder', 'हेल्थ ड्रिंक पाउडर'],
  ['Health Drink', 'हेल्थ ड्रिंक'],
  ['Detergent Powder', 'डिटर्जेंट पाउडर'],
  ['Liquid Detergent', 'लिक्विड डिटर्जेंट'],
  ['Washing Powder', 'वॉशिंग पाउडर'],
  ['Dishwash Gel', 'डिशवॉश जेल'],
  ['Dishwash Bar', 'डिशवॉश बार'],
  ['Liquid Dishwash', 'लिक्विड डिशवॉश'],
  ['Floor Cleaner', 'फ्लोर क्लीनर'],
  ['Toilet Cleaner', 'टॉयलेट क्लीनर'],
  ['Household Cleaner', 'हाउसहोल्ड क्लीनर'],
  ['Baby Diaper Pants', 'बेबी डायपर पैंट'],
  ['Baby Wipes', 'बेबी वाइप्स'],
  ['Baby Shampoo', 'बेबी शैंपू'],
  ['Bathing Soap Bar', 'नहाने का साबुन'],
  ['Bathing Bar', 'बाथिंग बार'],
  ['Toothpaste', 'टूथपेस्ट'],
  ['Toothbrush', 'टूथब्रश'],
  ['Coconut Hair Oil', 'नारियल हेयर ऑयल'],
  ['Hair Oil', 'हेयर ऑयल'],
  ['Hair Serum', 'हेयर सीरम'],
  ['Hair Shampoo', 'हेयर शैंपू'],
  ['Hair Conditioner', 'हेयर कंडीशनर'],
  ['Hair Mask', 'हेयर मास्क'],
  ['Anti-Dandruff Shampoo', 'एंटी-डैंड्रफ शैंपू'],
  ['Shampoo', 'शैंपू'],
  ['Handwash', 'हैंडवॉश'],
  ['Hand Sanitizer', 'हैंड सैनिटाइज़र'],
  ['Moisturising Cream', 'मॉइस्चराइज़िंग क्रीम'],
  ['Face Wash', 'फेस वॉश'],
  ['Face Serum', 'फेस सीरम'],
  ['Face Scrub', 'फेस स्क्रब'],
  ['Face Powder', 'फेस पाउडर'],
  ['Baby Lotion', 'बेबी लोशन'],
  ['Baby Powder', 'बेबी पाउडर'],
  ['Fabric Conditioner', 'फैब्रिक कंडीशनर'],
  ['Mosquito Vaporizer Refill', 'मच्छर रिपेलेंट रिफिल'],
  ['Mosquito Repellent Liquid Refill', 'मच्छर रिपेलेंट लिक्विड रिफिल'],
  ['Sunscreen', 'सनस्क्रीन'],
  ['Moisturizer', 'मॉइस्चराइज़र'],
  ['Sheet Mask', 'शीट मास्क'],
  ['Body Lotion', 'बॉडी लोशन'],
  ['Body Wash', 'बॉडी वॉश'],
  ['Shower Gel', 'शावर जेल'],
  ['Petroleum Jelly', 'पेट्रोलियम जेली'],
  ['Skin Cream', 'स्किन क्रीम'],
  ['Cold Cream', 'कोल्ड क्रीम'],
  ['Shaving Foam', 'शेविंग फोम'],
  ['After Shave Lotion', 'आफ्टर शेव लोशन'],
  ['Beard Oil', 'बियर्ड ऑयल'],
  ['Body Spray', 'बॉडी स्प्रे'],
  ['Deodorant', 'डिओडोरेंट'],
  ['Perfumed Talc', 'परफ्यूम्ड टाल्क'],
  ['Sanitary Pads', 'सैनिटरी पैड'],
  ['Liquid Foundation', 'लिक्विड फाउंडेशन'],
  ['Compact Powder', 'कॉम्पैक्ट पाउडर'],
  ['Mascara', 'मसकारा'],
  ['Liquid Eyeliner', 'लिक्विड आईलाइनर'],
  ['Liquid Lipstick', 'लिक्विड लिपस्टिक'],
  ['Kajal', 'काजल'],
  ['Lip Color', 'लिप कलर'],
  ['CC Cream', 'सीसी क्रीम'],
  ['Lipstick', 'लिपस्टिक'],
  ['Highlighter', 'हाइलाइटर'],
  ['Lip Balm', 'लिप बाम'],
  ['Condoms', 'कंडोम'],
  ['Replacement Cartridges', 'रिप्लेसमेंट कार्ट्रिज'],
  ['Razor', 'रेज़र'],
  ['Post Shave Balm', 'पोस्ट शेव बाम'],
  ['Perfume', 'परफ्यूम'],
  ['Disinfectant Liquid', 'एंटीसेप्टिक लिक्विड'],
  ['Glass Cleaner', 'ग्लास क्लीनर'],
  ['Dhaniya Powder', 'धनिया पाउडर'],
  ['Lal Mirch Powder', 'लाल मिर्च पाउडर'],
  ['Haldi Powder', 'हल्दी पाउडर'],
  ['Bandhani Hing', 'बांधनी हींग'],
  ['Bhujia Sev', 'भुजिया सेव'],
  ['Crispy Moong Dal', 'क्रिस्पी मूंग दाल'],
  ['Plain Boondi', 'प्लेन बूंदी'],
  ['Navrattan Mixture', 'नवरत्न मिक्स्चर'],
  ['Panchrattan Mixture', 'पंचरत्न मिक्स्चर'],
  ['All In One Mixture', 'ऑल इन वन मिक्स्चर'],
  ['Spiced Peanuts', 'मसालेदार मूंफली'],
  ['Masala Chana Dal', 'मसाला चना दाल'],
  ['Unpolished', 'अनपॉलिश्ड'],
  ['Pure Honey', 'शुद्ध शहद'],
  ['Value Pack', 'वैल्यू पैक'],
  ['Saver Pack', 'सेवर पैक'],
  ['Multipack', 'मल्टीपैक'],
  ['Pack', 'पैक'],
  ['Pouch', 'पाउच'],
  ['Bottle', 'बोतल'],
  ['Carton', 'कार्टन'],
  ['Jar', 'जार'],
  ['Tube', 'ट्यूब'],
  ['Box', 'बॉक्स'],
  ['Tin', 'टिन'],
  ['Can', 'कैन'],
  ['Pump', 'पंप'],
  ['Stick', 'स्टिक'],
  ['Dropper', 'ड्रॉपर'],
  ['Refill', 'रिफिल'],
  ['Tetra', 'टेट्रा'],
  ['Tetrapack', 'टेट्रापैक'],
  ['Pack of', 'का पैक'],
];

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function toHindiProductName(englishName: string): string {
  let text = englishName.trim();
  text = text.replace(/(\d+(?:\.\d+)?)kg\b/gi, '$1 किग्रा');
  text = text.replace(/(\d+(?:\.\d+)?)g\b/gi, '$1 ग्राम');
  text = text.replace(/(\d+(?:\.\d+)?)ml\b/gi, '$1 मि.ली.');
  text = text.replace(/(\d+(?:\.\d+)?)L\b/g, '$1 लीटर');
  text = text.replace(/\b(\d+)s\b/g, '$1 पीस');
  text = text.replace(/\(Pack of (\d+)\)/gi, '($1 का पैक)');
  text = text.replace(/Buy 2 Get 1 Free/gi, '2 खरीदें 1 मुफ्त');

  for (const [english, hindi] of NAME_PHRASES) {
    text = text.replace(new RegExp(escapeRegExp(english), 'gi'), hindi);
  }

  return text.replace(/\s+/g, ' ').trim().slice(0, 180);
}

export function hindiLabel(map: Record<string, string>, english: string): string {
  return map[english] ?? english;
}
